version: '3.3'

services:
  web:
    container_name: crt2_web
    image: nginx
    volumes:
      - ./app:/var/www/public
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    restart: always
    depends_on:
      - app
      - database

  app:
    container_name: crt2_app
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
    env_file:
      - ./.env
    volumes:
      - ./app/:/var/www/public/

  database:
    container_name: crt2_db
    image: postgres
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./postgres:/data/postgres

volumes:
  postgres: